const arabicLetters = [
  { letter: 'ا', transliteration: 'Alif' },
  { letter: 'ب', transliteration: 'Ba' },
  { letter: 'ت', transliteration: 'Ta' },
  { letter: 'ث', transliteration: 'Tha' },
  { letter: 'ج', transliteration: 'Jeem' },
  { letter: 'ح', transliteration: 'Ha' },
  { letter: 'خ', transliteration: 'Kho' },
  { letter: 'د', transliteration: 'Dal' },
  { letter: 'ذ', transliteration: 'Dhal' },
  { letter: 'ر', transliteration: 'Ro' },
  { letter: 'ز', transliteration: 'Za' },
  { letter: 'س', transliteration: 'Seen' },
  { letter: 'ش', transliteration: 'Sheen' },
  { letter: 'ص', transliteration: 'Sood' },
  { letter: 'ض', transliteration: 'Dood' },
  { letter: 'ط', transliteration: 'To' },
  { letter: 'ظ', transliteration: 'Zo' },
  { letter: 'ع', transliteration: 'Ayn' },
  { letter: 'غ', transliteration: 'Ghayn' },
  { letter: 'ف', transliteration: 'Fa' },
  { letter: 'ق', transliteration: 'Qoof' },
  { letter: 'ك', transliteration: 'Kaaf' },
  { letter: 'ل', transliteration: 'Laam' },
  { letter: 'م', transliteration: 'Meem' },
  { letter: 'ن', transliteration: 'Noon' },
  { letter: 'ه', transliteration: 'Haa' },
  { letter: 'و', transliteration: 'Waw' },
  { letter: 'ي', transliteration: 'Ya' },
];

export default arabicLetters;
